services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: time-sync-backend
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=postgres://admin:password@postgres:5432/timesync
      - NODE_ENV=development
    ports:
      - "3000:3000"